#!/bin/bash
# mock-agent.sh - Mock coding agent for testing markplane-ralph-epic
#
# This simulates an AI coding agent that:
# - Reports epic info (EPIC_ID, EPIC_NAME, DEPENDS_ON)
# - Creates files to simulate work
# - Commits when allowed
# - Signals epic/project completion
#
# Usage: mock-agent.sh "<prompt>"
#
# The mock maintains state in .mock-agent-state to track progress across iterations.

PROMPT="$1"
WORK_DIR=$(pwd)
MOCK_STATE_FILE="$WORK_DIR/.mock-agent-state"

# Load mock state (tracks which tasks are done)
TASK_COUNTER=0
CURRENT_EPIC=""
if [ -f "$MOCK_STATE_FILE" ]; then
    source "$MOCK_STATE_FILE"
fi

# Determine which epic to work on based on state
if [ -z "$CURRENT_EPIC" ]; then
    # Start with Epic 1
    CURRENT_EPIC="EPIC-001"
    TASK_COUNTER=0
fi

# Epic definitions (simulates what markplane would provide)
# Format: EPIC_ID|EPIC_NAME|DEPENDS_ON|TASKS_TOTAL
declare -A EPICS
EPICS["EPIC-001"]="User Authentication||2"
EPICS["EPIC-002"]="Dashboard UI|EPIC-001|2"
EPICS["EPIC-003"]="API Integration|EPIC-002|1"

# Check if all epics are done
if [ "$CURRENT_EPIC" = "DONE" ]; then
    echo "EPIC_ID: DONE"
    echo "All epics completed!"
    echo "RALPH_COMPLETE"
    exit 0
fi

# Parse current epic info
IFS='|' read -r EPIC_NAME DEPENDS_ON TASKS_TOTAL <<< "${EPICS[$CURRENT_EPIC]}"

# Increment task counter
TASK_COUNTER=$((TASK_COUNTER + 1))

# Output epic info (required by the script)
echo "EPIC_ID: $CURRENT_EPIC"
echo "EPIC_NAME: $EPIC_NAME"
echo "DEPENDS_ON: $DEPENDS_ON"
echo ""

# Simulate file creation (the actual "work")
TASK_FILE="$WORK_DIR/src/${CURRENT_EPIC,,}/task-${TASK_COUNTER}.ts"
mkdir -p "$(dirname "$TASK_FILE")"

cat > "$TASK_FILE" << EOF
// $EPIC_NAME - Task $TASK_COUNTER
// Epic: $CURRENT_EPIC
// Generated by mock-agent

export function task${TASK_COUNTER}() {
    console.log('Task $TASK_COUNTER for $EPIC_NAME implemented!');
    return { success: true, epic: '$CURRENT_EPIC', task: $TASK_COUNTER };
}
EOF

echo "📝 Working on: $EPIC_NAME"
echo "   Task $TASK_COUNTER of $TASKS_TOTAL"
echo "   Created: $TASK_FILE"
echo ""

# Check if this epic is complete
if [ $TASK_COUNTER -ge $TASKS_TOTAL ]; then
    echo "✅ All tasks in $EPIC_NAME completed!"
    echo ""
    echo "EPIC_COMPLETE"
    echo ""
    echo "PR_DESCRIPTION_START"
    echo "## $EPIC_NAME"
    echo ""
    echo "### Summary"
    echo "Implemented all $TASKS_TOTAL tasks for the $EPIC_NAME epic."
    echo ""
    echo "### Changes"
    for i in $(seq 1 $TASKS_TOTAL); do
        echo "- Task $i: Added implementation in \`src/${CURRENT_EPIC,,}/task-${i}.ts\`"
    done
    echo ""
    echo "### Testing"
    echo "All acceptance criteria have been verified."
    echo "PR_DESCRIPTION_END"
    
    # Determine next epic
    NEXT_EPIC=""
    case "$CURRENT_EPIC" in
        "EPIC-001") NEXT_EPIC="EPIC-002" ;;
        "EPIC-002") NEXT_EPIC="EPIC-003" ;;
        "EPIC-003") NEXT_EPIC="DONE" ;;
    esac
    
    # Save state for next iteration
    echo "CURRENT_EPIC=$NEXT_EPIC" > "$MOCK_STATE_FILE"
    echo "TASK_COUNTER=0" >> "$MOCK_STATE_FILE"
    
    # Check if ALL epics are done
    if [ "$NEXT_EPIC" = "DONE" ]; then
        echo ""
        echo "🎉 All epics completed!"
        echo "RALPH_COMPLETE"
    fi
else
    # Save state for next iteration (continue same epic)
    echo "CURRENT_EPIC=$CURRENT_EPIC" > "$MOCK_STATE_FILE"
    echo "TASK_COUNTER=$TASK_COUNTER" >> "$MOCK_STATE_FILE"
fi

# Check if we should commit (agent commits when on correct branch)
if echo "$PROMPT" | grep -q "You CAN and SHOULD commit"; then
    echo ""
    echo "💾 Committing changes..."
    git add .
    git commit -m "feat($CURRENT_EPIC): implement task $TASK_COUNTER for $EPIC_NAME"
fi

echo ""
echo "--- Mock agent iteration complete ---"
